In [2]:
import pandas as pd
df = pd.read_csv("data.csv")
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'  110.0     130.0     409.1
1         60  '2020/12/02'  117.0     145.0     479.0
2         60  '2020/12/03'  103.0     135.0     340.0
3         45  '2020/12/04'  109.0     175.0     282.4
4         45  '2020/12/05'  117.0     148.0     406.0
5         60  '2020/12/06'  102.0     127.0     300.0
6         60  '2020/12/07'  110.0     136.0     374.0
7        450  '2020/12/08'  104.0       NaN     253.3
8         30  '2020/12/09'  109.0     133.0     195.1
9         60  '2020/12/10'   98.0     124.0     269.0
10        60  '2020/12/11'  103.0     147.0     329.3
11        60  '2020/12/12'  100.0     120.0     250.7
12        60  '2020/12/12'  100.0     120.0     250.7
13        60  '2020/12/13'  106.0     128.0     345.3
14        60  '2020/12/14'    NaN     132.0     379.3
15        60  '2020/12/15'   98.0     123.0     275.0
16        60  '2020/12/16'   98.0     120.0     215.2
17        60  '2020/12/17'  100.0     120.0     300.0
18        45  '2020/12/18'   90.0     112.0       NaN
19        60  '2020/12/19'  103.0     123.0     323.0
20        45  '2020/12/20'   97.0     125.0     243.0
21        60  '2020/12/21'  108.0     131.0     364.2
22        45           NaN  100.0     119.0     282.0
23        60  '2020/12/23'  130.0     101.0     300.0
24        45  '2020/12/24'  105.0     132.0     246.0
25        60  '2020/12/25'  102.0     126.0     334.5
26        60      20201226  100.0     120.0     250.0
27        60  '2020/12/27'   92.0     118.0     241.0
28        60  '2020/12/28'  103.0     132.0       NaN
29        60  '2020/12/29'  100.0     132.0     280.0
30        60  '2020/12/30'  102.0     129.0     380.3
31        60  '2020/12/31'   92.0     115.0     243.0

In [29]:
# loc and iloc is used to locate rows
# df.loc[20]
df

              Duration  Pulse  Maxpulse  Calories
Date
'2020/12/01'        60  110.0     130.0     409.1
'2020/12/02'        60  117.0     145.0     479.0
'2020/12/03'        60  103.0     135.0     340.0
'2020/12/04'        45  109.0     175.0     282.4
'2020/12/05'        45  117.0     148.0     406.0
'2020/12/06'        60  102.0     127.0     300.0
'2020/12/07'        60  110.0     136.0     374.0
'2020/12/08'       450  104.0       NaN     253.3
'2020/12/09'        30  109.0     133.0     195.1
'2020/12/10'        60   98.0     124.0     269.0
'2020/12/11'        60  103.0     147.0     329.3
'2020/12/12'        60  100.0     120.0     250.7
'2020/12/12'        60  100.0     120.0     250.7
'2020/12/13'        60  106.0     128.0     345.3
'2020/12/14'        60    NaN     132.0     379.3
'2020/12/15'        60   98.0     123.0     275.0
'2020/12/16'        60   98.0     120.0     215.2
'2020/12/17'        60  100.0     120.0     300.0
'2020/12/18'        45   90.0     112.0       NaN
'2020/12/19'        60  103.0     123.0     323.0
'2020/12/20'        45   97.0     125.0     243.0
'2020/12/21'        60  108.0     131.0     364.2
NaN                 45  100.0     119.0     282.0
'2020/12/23'        60  130.0     101.0     300.0
'2020/12/24'        45  105.0     132.0     246.0
'2020/12/25'        60  102.0     126.0     334.5
20201226            60  100.0     120.0     250.0
'2020/12/27'        60   92.0     118.0     241.0
'2020/12/28'        60  103.0     132.0       NaN
'2020/12/29'        60  100.0     132.0     280.0
'2020/12/30'        60  102.0     129.0     380.3
'2020/12/31'        60   92.0     115.0     243.0

In [28]:
dfm = df.copy()
dfm

              Duration  Pulse  Maxpulse  Calories
Date
'2020/12/01'        60  110.0     130.0     409.1
'2020/12/02'        60  117.0     145.0     479.0
'2020/12/03'        60  103.0     135.0     340.0
'2020/12/04'        45  109.0     175.0     282.4
'2020/12/05'        45  117.0     148.0     406.0
'2020/12/06'        60  102.0     127.0     300.0
'2020/12/07'        60  110.0     136.0     374.0
'2020/12/08'       450  104.0       NaN     253.3
'2020/12/09'        30  109.0     133.0     195.1
'2020/12/10'        60   98.0     124.0     269.0
'2020/12/11'        60  103.0     147.0     329.3
'2020/12/12'        60  100.0     120.0     250.7
'2020/12/12'        60  100.0     120.0     250.7
'2020/12/13'        60  106.0     128.0     345.3
'2020/12/14'        60    NaN     132.0     379.3
'2020/12/15'        60   98.0     123.0     275.0
'2020/12/16'        60   98.0     120.0     215.2
'2020/12/17'        60  100.0     120.0     300.0
'2020/12/18'        45   90.0     112.0       NaN
'2020/12/19'        60  103.0     123.0     323.0
'2020/12/20'        45   97.0     125.0     243.0
'2020/12/21'        60  108.0     131.0     364.2
NaN                 45  100.0     119.0     282.0
'2020/12/23'        60  130.0     101.0     300.0
'2020/12/24'        45  105.0     132.0     246.0
'2020/12/25'        60  102.0     126.0     334.5
20201226            60  100.0     120.0     250.0
'2020/12/27'        60   92.0     118.0     241.0
'2020/12/28'        60  103.0     132.0       NaN
'2020/12/29'        60  100.0     132.0     280.0
'2020/12/30'        60  102.0     129.0     380.3
'2020/12/31'        60   92.0     115.0     243.0

In [35]:
dfm.set_index(inplace = True, keys = "Maxpulse")
dfm

KeyError: "None of ['Maxpulse'] are in the columns"

In [36]:
da = pd.read_csv("data.csv")

In [37]:
da

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'  110.0     130.0     409.1
1         60  '2020/12/02'  117.0     145.0     479.0
2         60  '2020/12/03'  103.0     135.0     340.0
3         45  '2020/12/04'  109.0     175.0     282.4
4         45  '2020/12/05'  117.0     148.0     406.0
5         60  '2020/12/06'  102.0     127.0     300.0
6         60  '2020/12/07'  110.0     136.0     374.0
7        450  '2020/12/08'  104.0       NaN     253.3
8         30  '2020/12/09'  109.0     133.0     195.1
9         60  '2020/12/10'   98.0     124.0     269.0
10        60  '2020/12/11'  103.0     147.0     329.3
11        60  '2020/12/12'  100.0     120.0     250.7
12        60  '2020/12/12'  100.0     120.0     250.7
13        60  '2020/12/13'  106.0     128.0     345.3
14        60  '2020/12/14'    NaN     132.0     379.3
15        60  '2020/12/15'   98.0     123.0     275.0
16        60  '2020/12/16'   98.0     120.0     215.2
17        60  '2020/12/17'  100.0     120.0     300.0
18        45  '2020/12/18'   90.0     112.0       NaN
19        60  '2020/12/19'  103.0     123.0     323.0
20        45  '2020/12/20'   97.0     125.0     243.0
21        60  '2020/12/21'  108.0     131.0     364.2
22        45           NaN  100.0     119.0     282.0
23        60  '2020/12/23'  130.0     101.0     300.0
24        45  '2020/12/24'  105.0     132.0     246.0
25        60  '2020/12/25'  102.0     126.0     334.5
26        60      20201226  100.0     120.0     250.0
27        60  '2020/12/27'   92.0     118.0     241.0
28        60  '2020/12/28'  103.0     132.0       NaN
29        60  '2020/12/29'  100.0     132.0     280.0
30        60  '2020/12/30'  102.0     129.0     380.3
31        60  '2020/12/31'   92.0     115.0     243.0

In [38]:
da.iloc[13]

Duration              60
Date        '2020/12/13'
Pulse              106.0
Maxpulse           128.0
Calories           345.3
Name: 13, dtype: object

In [39]:
da = da.rename(columns = {'Duration':'Time'})

In [40]:
da

    Time          Date  Pulse  Maxpulse  Calories
0     60  '2020/12/01'  110.0     130.0     409.1
1     60  '2020/12/02'  117.0     145.0     479.0
2     60  '2020/12/03'  103.0     135.0     340.0
3     45  '2020/12/04'  109.0     175.0     282.4
4     45  '2020/12/05'  117.0     148.0     406.0
5     60  '2020/12/06'  102.0     127.0     300.0
6     60  '2020/12/07'  110.0     136.0     374.0
7    450  '2020/12/08'  104.0       NaN     253.3
8     30  '2020/12/09'  109.0     133.0     195.1
9     60  '2020/12/10'   98.0     124.0     269.0
10    60  '2020/12/11'  103.0     147.0     329.3
11    60  '2020/12/12'  100.0     120.0     250.7
12    60  '2020/12/12'  100.0     120.0     250.7
13    60  '2020/12/13'  106.0     128.0     345.3
14    60  '2020/12/14'    NaN     132.0     379.3
15    60  '2020/12/15'   98.0     123.0     275.0
16    60  '2020/12/16'   98.0     120.0     215.2
17    60  '2020/12/17'  100.0     120.0     300.0
18    45  '2020/12/18'   90.0     112.0       NaN
19    60  '2020/12/19'  103.0     123.0     323.0
20    45  '2020/12/20'   97.0     125.0     243.0
21    60  '2020/12/21'  108.0     131.0     364.2
22    45           NaN  100.0     119.0     282.0
23    60  '2020/12/23'  130.0     101.0     300.0
24    45  '2020/12/24'  105.0     132.0     246.0
25    60  '2020/12/25'  102.0     126.0     334.5
26    60      20201226  100.0     120.0     250.0
27    60  '2020/12/27'   92.0     118.0     241.0
28    60  '2020/12/28'  103.0     132.0       NaN
29    60  '2020/12/29'  100.0     132.0     280.0
30    60  '2020/12/30'  102.0     129.0     380.3
31    60  '2020/12/31'   92.0     115.0     243.0

In [41]:
da = da.dropna()

In [42]:
da

    Time          Date  Pulse  Maxpulse  Calories
0     60  '2020/12/01'  110.0     130.0     409.1
1     60  '2020/12/02'  117.0     145.0     479.0
2     60  '2020/12/03'  103.0     135.0     340.0
3     45  '2020/12/04'  109.0     175.0     282.4
4     45  '2020/12/05'  117.0     148.0     406.0
5     60  '2020/12/06'  102.0     127.0     300.0
6     60  '2020/12/07'  110.0     136.0     374.0
8     30  '2020/12/09'  109.0     133.0     195.1
9     60  '2020/12/10'   98.0     124.0     269.0
10    60  '2020/12/11'  103.0     147.0     329.3
11    60  '2020/12/12'  100.0     120.0     250.7
12    60  '2020/12/12'  100.0     120.0     250.7
13    60  '2020/12/13'  106.0     128.0     345.3
15    60  '2020/12/15'   98.0     123.0     275.0
16    60  '2020/12/16'   98.0     120.0     215.2
17    60  '2020/12/17'  100.0     120.0     300.0
19    60  '2020/12/19'  103.0     123.0     323.0
20    45  '2020/12/20'   97.0     125.0     243.0
21    60  '2020/12/21'  108.0     131.0     364.2
23    60  '2020/12/23'  130.0     101.0     300.0
24    45  '2020/12/24'  105.0     132.0     246.0
25    60  '2020/12/25'  102.0     126.0     334.5
26    60      20201226  100.0     120.0     250.0
27    60  '2020/12/27'   92.0     118.0     241.0
29    60  '2020/12/29'  100.0     132.0     280.0
30    60  '2020/12/30'  102.0     129.0     380.3
31    60  '2020/12/31'   92.0     115.0     243.0

In [43]:
da.dtypes

Time          int64
Date         object
Pulse       float64
Maxpulse    float64
Calories    float64
dtype: object

In [46]:
da['Final'] = da['Calories'] + da['Pulse']

C:\Users\rohit\AppData\Local\Temp\ipykernel_22748\49912070.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  da['Final'] = da['Calories'] + da['Pulse']

In [47]:
da

    Time          Date  Pulse  Maxpulse  Calories    Set  Final
0     60  '2020/12/01'  110.0     130.0     409.1  240.0  519.1
1     60  '2020/12/02'  117.0     145.0     479.0  262.0  596.0
2     60  '2020/12/03'  103.0     135.0     340.0  238.0  443.0
3     45  '2020/12/04'  109.0     175.0     282.4  284.0  391.4
4     45  '2020/12/05'  117.0     148.0     406.0  265.0  523.0
5     60  '2020/12/06'  102.0     127.0     300.0  229.0  402.0
6     60  '2020/12/07'  110.0     136.0     374.0  246.0  484.0
8     30  '2020/12/09'  109.0     133.0     195.1  242.0  304.1
9     60  '2020/12/10'   98.0     124.0     269.0  222.0  367.0
10    60  '2020/12/11'  103.0     147.0     329.3  250.0  432.3
11    60  '2020/12/12'  100.0     120.0     250.7  220.0  350.7
12    60  '2020/12/12'  100.0     120.0     250.7  220.0  350.7
13    60  '2020/12/13'  106.0     128.0     345.3  234.0  451.3
15    60  '2020/12/15'   98.0     123.0     275.0  221.0  373.0
16    60  '2020/12/16'   98.0     120.0     215.2  218.0  313.2
17    60  '2020/12/17'  100.0     120.0     300.0  220.0  400.0
19    60  '2020/12/19'  103.0     123.0     323.0  226.0  426.0
20    45  '2020/12/20'   97.0     125.0     243.0  222.0  340.0
21    60  '2020/12/21'  108.0     131.0     364.2  239.0  472.2
23    60  '2020/12/23'  130.0     101.0     300.0  231.0  430.0
24    45  '2020/12/24'  105.0     132.0     246.0  237.0  351.0
25    60  '2020/12/25'  102.0     126.0     334.5  228.0  436.5
26    60      20201226  100.0     120.0     250.0  220.0  350.0
27    60  '2020/12/27'   92.0     118.0     241.0  210.0  333.0
29    60  '2020/12/29'  100.0     132.0     280.0  232.0  380.0
30    60  '2020/12/30'  102.0     129.0     380.3  231.0  482.3
31    60  '2020/12/31'   92.0     115.0     243.0  207.0  335.0

In [54]:
# Drop row

da = da.drop(30)

In [55]:
da

    Time          Date  Pulse  Maxpulse  Calories    Set  Final
0     60  '2020/12/01'  110.0     130.0     409.1  240.0  519.1
1     60  '2020/12/02'  117.0     145.0     479.0  262.0  596.0
2     60  '2020/12/03'  103.0     135.0     340.0  238.0  443.0
3     45  '2020/12/04'  109.0     175.0     282.4  284.0  391.4
4     45  '2020/12/05'  117.0     148.0     406.0  265.0  523.0
5     60  '2020/12/06'  102.0     127.0     300.0  229.0  402.0
6     60  '2020/12/07'  110.0     136.0     374.0  246.0  484.0
8     30  '2020/12/09'  109.0     133.0     195.1  242.0  304.1
9     60  '2020/12/10'   98.0     124.0     269.0  222.0  367.0
10    60  '2020/12/11'  103.0     147.0     329.3  250.0  432.3
11    60  '2020/12/12'  100.0     120.0     250.7  220.0  350.7
12    60  '2020/12/12'  100.0     120.0     250.7  220.0  350.7
13    60  '2020/12/13'  106.0     128.0     345.3  234.0  451.3
15    60  '2020/12/15'   98.0     123.0     275.0  221.0  373.0
16    60  '2020/12/16'   98.0     120.0     215.2  218.0  313.2
17    60  '2020/12/17'  100.0     120.0     300.0  220.0  400.0
19    60  '2020/12/19'  103.0     123.0     323.0  226.0  426.0
20    45  '2020/12/20'   97.0     125.0     243.0  222.0  340.0
21    60  '2020/12/21'  108.0     131.0     364.2  239.0  472.2
23    60  '2020/12/23'  130.0     101.0     300.0  231.0  430.0
24    45  '2020/12/24'  105.0     132.0     246.0  237.0  351.0
25    60  '2020/12/25'  102.0     126.0     334.5  228.0  436.5
26    60      20201226  100.0     120.0     250.0  220.0  350.0
27    60  '2020/12/27'   92.0     118.0     241.0  210.0  333.0
29    60  '2020/12/29'  100.0     132.0     280.0  232.0  380.0
31    60  '2020/12/31'   92.0     115.0     243.0  207.0  335.0

In [56]:
da = da.drop('Pulse', axis = 1)

In [57]:
da

    Time          Date  Maxpulse  Calories    Set  Final
0     60  '2020/12/01'     130.0     409.1  240.0  519.1
1     60  '2020/12/02'     145.0     479.0  262.0  596.0
2     60  '2020/12/03'     135.0     340.0  238.0  443.0
3     45  '2020/12/04'     175.0     282.4  284.0  391.4
4     45  '2020/12/05'     148.0     406.0  265.0  523.0
5     60  '2020/12/06'     127.0     300.0  229.0  402.0
6     60  '2020/12/07'     136.0     374.0  246.0  484.0
8     30  '2020/12/09'     133.0     195.1  242.0  304.1
9     60  '2020/12/10'     124.0     269.0  222.0  367.0
10    60  '2020/12/11'     147.0     329.3  250.0  432.3
11    60  '2020/12/12'     120.0     250.7  220.0  350.7
12    60  '2020/12/12'     120.0     250.7  220.0  350.7
13    60  '2020/12/13'     128.0     345.3  234.0  451.3
15    60  '2020/12/15'     123.0     275.0  221.0  373.0
16    60  '2020/12/16'     120.0     215.2  218.0  313.2
17    60  '2020/12/17'     120.0     300.0  220.0  400.0
19    60  '2020/12/19'     123.0     323.0  226.0  426.0
20    45  '2020/12/20'     125.0     243.0  222.0  340.0
21    60  '2020/12/21'     131.0     364.2  239.0  472.2
23    60  '2020/12/23'     101.0     300.0  231.0  430.0
24    45  '2020/12/24'     132.0     246.0  237.0  351.0
25    60  '2020/12/25'     126.0     334.5  228.0  436.5
26    60      20201226     120.0     250.0  220.0  350.0
27    60  '2020/12/27'     118.0     241.0  210.0  333.0
29    60  '2020/12/29'     132.0     280.0  232.0  380.0
31    60  '2020/12/31'     115.0     243.0  207.0  335.0

In [62]:
da.iloc[[2,6],[0,5]]

   Time  Final
2    60  443.0
6    60  484.0

In [68]:
da['Maxpulse']>130

0     False
1      True
2      True
3      True
4      True
5     False
6      True
8      True
9     False
10     True
11    False
12    False
13    False
15    False
16    False
17    False
19    False
20    False
21     True
23    False
24     True
25    False
26    False
27    False
29     True
31    False
Name: Maxpulse, dtype: bool

In [69]:
da[da['Maxpulse']>130] #Shows only True rows

    Time          Date  Maxpulse  Calories    Set  Final
1     60  '2020/12/02'     145.0     479.0  262.0  596.0
2     60  '2020/12/03'     135.0     340.0  238.0  443.0
3     45  '2020/12/04'     175.0     282.4  284.0  391.4
4     45  '2020/12/05'     148.0     406.0  265.0  523.0
6     60  '2020/12/07'     136.0     374.0  246.0  484.0
8     30  '2020/12/09'     133.0     195.1  242.0  304.1
10    60  '2020/12/11'     147.0     329.3  250.0  432.3
21    60  '2020/12/21'     131.0     364.2  239.0  472.2
24    45  '2020/12/24'     132.0     246.0  237.0  351.0
29    60  '2020/12/29'     132.0     280.0  232.0  380.0

In [70]:
d1 = da['Final'] > 400
d1

0      True
1      True
2      True
3     False
4      True
5      True
6      True
8     False
9     False
10     True
11    False
12    False
13     True
15    False
16    False
17    False
19     True
20    False
21     True
23     True
24    False
25     True
26    False
27    False
29    False
31    False
Name: Final, dtype: bool

In [71]:
d2 = da['Maxpulse'] > 130
d2

0     False
1      True
2      True
3      True
4      True
5     False
6      True
8      True
9     False
10     True
11    False
12    False
13    False
15    False
16    False
17    False
19    False
20    False
21     True
23    False
24     True
25    False
26    False
27    False
29     True
31    False
Name: Maxpulse, dtype: bool

In [73]:
da[d1 & d2]

    Time          Date  Maxpulse  Calories    Set  Final
1     60  '2020/12/02'     145.0     479.0  262.0  596.0
2     60  '2020/12/03'     135.0     340.0  238.0  443.0
4     45  '2020/12/05'     148.0     406.0  265.0  523.0
6     60  '2020/12/07'     136.0     374.0  246.0  484.0
10    60  '2020/12/11'     147.0     329.3  250.0  432.3
21    60  '2020/12/21'     131.0     364.2  239.0  472.2

In [74]:
da[d1 | d2]

    Time          Date  Maxpulse  Calories    Set  Final
0     60  '2020/12/01'     130.0     409.1  240.0  519.1
1     60  '2020/12/02'     145.0     479.0  262.0  596.0
2     60  '2020/12/03'     135.0     340.0  238.0  443.0
3     45  '2020/12/04'     175.0     282.4  284.0  391.4
4     45  '2020/12/05'     148.0     406.0  265.0  523.0
5     60  '2020/12/06'     127.0     300.0  229.0  402.0
6     60  '2020/12/07'     136.0     374.0  246.0  484.0
8     30  '2020/12/09'     133.0     195.1  242.0  304.1
10    60  '2020/12/11'     147.0     329.3  250.0  432.3
13    60  '2020/12/13'     128.0     345.3  234.0  451.3
19    60  '2020/12/19'     123.0     323.0  226.0  426.0
21    60  '2020/12/21'     131.0     364.2  239.0  472.2
23    60  '2020/12/23'     101.0     300.0  231.0  430.0
24    45  '2020/12/24'     132.0     246.0  237.0  351.0
25    60  '2020/12/25'     126.0     334.5  228.0  436.5
29    60  '2020/12/29'     132.0     280.0  232.0  380.0

In [76]:
da.set_index(inplace = True, keys='Set')

In [77]:
da

       Time          Date  Maxpulse  Calories  Final
Set
240.0    60  '2020/12/01'     130.0     409.1  519.1
262.0    60  '2020/12/02'     145.0     479.0  596.0
238.0    60  '2020/12/03'     135.0     340.0  443.0
284.0    45  '2020/12/04'     175.0     282.4  391.4
265.0    45  '2020/12/05'     148.0     406.0  523.0
229.0    60  '2020/12/06'     127.0     300.0  402.0
246.0    60  '2020/12/07'     136.0     374.0  484.0
242.0    30  '2020/12/09'     133.0     195.1  304.1
222.0    60  '2020/12/10'     124.0     269.0  367.0
250.0    60  '2020/12/11'     147.0     329.3  432.3
220.0    60  '2020/12/12'     120.0     250.7  350.7
220.0    60  '2020/12/12'     120.0     250.7  350.7
234.0    60  '2020/12/13'     128.0     345.3  451.3
221.0    60  '2020/12/15'     123.0     275.0  373.0
218.0    60  '2020/12/16'     120.0     215.2  313.2
220.0    60  '2020/12/17'     120.0     300.0  400.0
226.0    60  '2020/12/19'     123.0     323.0  426.0
222.0    45  '2020/12/20'     125.0     243.0  340.0
239.0    60  '2020/12/21'     131.0     364.2  472.2
231.0    60  '2020/12/23'     101.0     300.0  430.0
237.0    45  '2020/12/24'     132.0     246.0  351.0
228.0    60  '2020/12/25'     126.0     334.5  436.5
220.0    60      20201226     120.0     250.0  350.0
210.0    60  '2020/12/27'     118.0     241.0  333.0
232.0    60  '2020/12/29'     132.0     280.0  380.0
207.0    60  '2020/12/31'     115.0     243.0  335.0

In [88]:
da.set_index(inplace = True, keys='Set')

KeyError: "None of ['Set'] are in the columns"

In [89]:
da

       index  Time          Date  Maxpulse  Calories  Final
Set
240.0      0    60  '2020/12/01'     130.0     409.1  519.1
262.0      1    60  '2020/12/02'     145.0     479.0  596.0
238.0      2    60  '2020/12/03'     135.0     340.0  443.0
284.0      3    45  '2020/12/04'     175.0     282.4  391.4
265.0      4    45  '2020/12/05'     148.0     406.0  523.0
229.0      5    60  '2020/12/06'     127.0     300.0  402.0
246.0      6    60  '2020/12/07'     136.0     374.0  484.0
242.0      7    30  '2020/12/09'     133.0     195.1  304.1
222.0      8    60  '2020/12/10'     124.0     269.0  367.0
250.0      9    60  '2020/12/11'     147.0     329.3  432.3
220.0     10    60  '2020/12/12'     120.0     250.7  350.7
220.0     11    60  '2020/12/12'     120.0     250.7  350.7
234.0     12    60  '2020/12/13'     128.0     345.3  451.3
221.0     13    60  '2020/12/15'     123.0     275.0  373.0
218.0     14    60  '2020/12/16'     120.0     215.2  313.2
220.0     15    60  '2020/12/17'     120.0     300.0  400.0
226.0     16    60  '2020/12/19'     123.0     323.0  426.0
222.0     17    45  '2020/12/20'     125.0     243.0  340.0
239.0     18    60  '2020/12/21'     131.0     364.2  472.2
231.0     19    60  '2020/12/23'     101.0     300.0  430.0
237.0     20    45  '2020/12/24'     132.0     246.0  351.0
228.0     21    60  '2020/12/25'     126.0     334.5  436.5
220.0     22    60      20201226     120.0     250.0  350.0
210.0     23    60  '2020/12/27'     118.0     241.0  333.0
232.0     24    60  '2020/12/29'     132.0     280.0  380.0
207.0     25    60  '2020/12/31'     115.0     243.0  335.0

In [90]:
da.reset_index(inplace = True, drop = True)

In [91]:
da

    index  Time          Date  Maxpulse  Calories  Final
0       0    60  '2020/12/01'     130.0     409.1  519.1
1       1    60  '2020/12/02'     145.0     479.0  596.0
2       2    60  '2020/12/03'     135.0     340.0  443.0
3       3    45  '2020/12/04'     175.0     282.4  391.4
4       4    45  '2020/12/05'     148.0     406.0  523.0
5       5    60  '2020/12/06'     127.0     300.0  402.0
6       6    60  '2020/12/07'     136.0     374.0  484.0
7       7    30  '2020/12/09'     133.0     195.1  304.1
8       8    60  '2020/12/10'     124.0     269.0  367.0
9       9    60  '2020/12/11'     147.0     329.3  432.3
10     10    60  '2020/12/12'     120.0     250.7  350.7
11     11    60  '2020/12/12'     120.0     250.7  350.7
12     12    60  '2020/12/13'     128.0     345.3  451.3
13     13    60  '2020/12/15'     123.0     275.0  373.0
14     14    60  '2020/12/16'     120.0     215.2  313.2
15     15    60  '2020/12/17'     120.0     300.0  400.0
16     16    60  '2020/12/19'     123.0     323.0  426.0
17     17    45  '2020/12/20'     125.0     243.0  340.0
18     18    60  '2020/12/21'     131.0     364.2  472.2
19     19    60  '2020/12/23'     101.0     300.0  430.0
20     20    45  '2020/12/24'     132.0     246.0  351.0
21     21    60  '2020/12/25'     126.0     334.5  436.5
22     22    60      20201226     120.0     250.0  350.0
23     23    60  '2020/12/27'     118.0     241.0  333.0
24     24    60  '2020/12/29'     132.0     280.0  380.0
25     25    60  '2020/12/31'     115.0     243.0  335.0