In [1]:
import pandas as pd

In [2]:
da = pd.read_csv('data.csv')

In [3]:
da

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'  110.0     130.0     409.1
1         60  '2020/12/02'  117.0     145.0     479.0
2         60  '2020/12/03'  103.0     135.0     340.0
3         45  '2020/12/04'  109.0     175.0     282.4
4         45  '2020/12/05'  117.0     148.0     406.0
5         60  '2020/12/06'  102.0     127.0     300.0
6         60  '2020/12/07'  110.0     136.0     374.0
7        450  '2020/12/08'  104.0       NaN     253.3
8         30  '2020/12/09'  109.0     133.0     195.1
9         60  '2020/12/10'   98.0     124.0     269.0
10        60  '2020/12/11'  103.0     147.0     329.3
11        60  '2020/12/12'  100.0     120.0     250.7
12        60  '2020/12/12'  100.0     120.0     250.7
13        60  '2020/12/13'  106.0     128.0     345.3
14        60  '2020/12/14'    NaN     132.0     379.3
15        60  '2020/12/15'   98.0     123.0     275.0
16        60  '2020/12/16'   98.0     120.0     215.2
17        60  '2020/12/17'  100.0     120.0     300.0
18        45  '2020/12/18'   90.0     112.0       NaN
19        60  '2020/12/19'  103.0     123.0     323.0
20        45  '2020/12/20'   97.0     125.0     243.0
21        60  '2020/12/21'  108.0     131.0     364.2
22        45           NaN  100.0     119.0     282.0
23        60  '2020/12/23'  130.0     101.0     300.0
24        45  '2020/12/24'  105.0     132.0     246.0
25        60  '2020/12/25'  102.0     126.0     334.5
26        60      20201226  100.0     120.0     250.0
27        60  '2020/12/27'   92.0     118.0     241.0
28        60  '2020/12/28'  103.0     132.0       NaN
29        60  '2020/12/29'  100.0     132.0     280.0
30        60  '2020/12/30'  102.0     129.0     380.3
31        60  '2020/12/31'   92.0     115.0     243.0

In [6]:
# Pulse is set as new index

da

       Duration          Date  Maxpulse  Calories
Pulse
110.0        60  '2020/12/01'     130.0     409.1
117.0        60  '2020/12/02'     145.0     479.0
103.0        60  '2020/12/03'     135.0     340.0
109.0        45  '2020/12/04'     175.0     282.4
117.0        45  '2020/12/05'     148.0     406.0
102.0        60  '2020/12/06'     127.0     300.0
110.0        60  '2020/12/07'     136.0     374.0
104.0       450  '2020/12/08'       NaN     253.3
109.0        30  '2020/12/09'     133.0     195.1
98.0         60  '2020/12/10'     124.0     269.0
103.0        60  '2020/12/11'     147.0     329.3
100.0        60  '2020/12/12'     120.0     250.7
100.0        60  '2020/12/12'     120.0     250.7
106.0        60  '2020/12/13'     128.0     345.3
NaN          60  '2020/12/14'     132.0     379.3
98.0         60  '2020/12/15'     123.0     275.0
98.0         60  '2020/12/16'     120.0     215.2
100.0        60  '2020/12/17'     120.0     300.0
90.0         45  '2020/12/18'     112.0       NaN
103.0        60  '2020/12/19'     123.0     323.0
97.0         45  '2020/12/20'     125.0     243.0
108.0        60  '2020/12/21'     131.0     364.2
100.0        45           NaN     119.0     282.0
130.0        60  '2020/12/23'     101.0     300.0
105.0        45  '2020/12/24'     132.0     246.0
102.0        60  '2020/12/25'     126.0     334.5
100.0        60      20201226     120.0     250.0
92.0         60  '2020/12/27'     118.0     241.0
103.0        60  '2020/12/28'     132.0       NaN
100.0        60  '2020/12/29'     132.0     280.0
102.0        60  '2020/12/30'     129.0     380.3
92.0         60  '2020/12/31'     115.0     243.0